### ISSUE TITLE
Cannot run ember serve on M1

### ISSUE THREAD

**Issue by ogirginc** [FrontendMasters/ember-octane#35]
I am on a M1 Macbook. When I try to run `ember serve` this is what I get:

```
> ember serve
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
WARNING: Node v16.14.0 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js. See https://git.io/v7S5n for details.
Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
⠋ building... JSON Server is running
⠦ building... [Babel: @ember/test-helpers > applyPatches]node:internal/validators:164
      throw new ERR_INVALID_ARG_TYPE(name, 'Object', value);
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "options" argument must be of type object. Received an instance of Array
    at ChildProcess.target.send (node:internal/child_process:733:7)
    at Array.forEach (<anonymous>)
    at dispatchQueuedRequests (/Users/ogirginc/Projects/shlack/node_modules/workerpool/lib/WorkerHandler.js:174:21)
    at ChildProcess.<anonymous> (/Users/ogirginc/Projects/shlack/node_modules/workerpool/lib/WorkerHandler.js:129:7)
    at ChildProcess.emit (node:events:520:28)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

Here are some additional data:

```
> ember --version
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
WARNING: Node v16.14.0 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js. See https://git.io/v7S5n for details.
ember-cli: 3.11.0-beta.3
node: 16.14.0
os: darwin arm64
```

Is there a quick fix I can apply to start the course?

**Comment by ogirginc** [comment]
I don't know if this is OK for the whole course, but I was able to run `ember server` by following https://github.com/ember-cli/ember-cli/issues/9404#issuecomment-857643079.

```
export NODE_OPTIONS="--require /Users/ogirginc/Projects/node-15-for-ember-monkeypatching.js" && ember serve
```

**Comment by lbrowngs** [comment]
> 

This fix worked for me as well, although I haven't tested it through the whole course yet.
